# CH-AWS
# 13_meteo_pressure


AWS13-RAW-CSV-1MIN-202001010100:
  # TOA5
  # First file: CH-AWS_EC_Press-202001010100.csv (the very first CH-AWS_EC_Press-*.csv file)
  # Last file:  *currently running*
  # Pressure from the LI-7500, eddy covariance measurements
  filetype_valid_from: 2020-01-01 01:00:00
  filetype_valid_to: 2099-12-31 23:59:59
  filetype_id: CH-AWS_EC_Press-*.csv
  filetype_dateparser: CH-AWS_EC_Press-%Y%m%d%H%M.csv
  filetype_gzip: false
  db_bucket: ch-aws_raw
  filegroup: 13_meteo_pressure
  data_raw_freq: T
  data_skiprows: [ ]
  data_headerrows: [ 0 ]
  data_index_col: 0
  data_parse_dates: [ 0 ]
  data_date_parser: '%Y-%m-%d %H:%M:%S'
  data_build_timestamp: false
  data_keep_good_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: utf-8
  data_delimiter: ','
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    PA_T1_1.3_1_1: { field: PA_T1_1.3_1, units: hPa, measurement: PA }
    N_PA_T1_1.3_1_1: { field: NUMVALS_PA_T1_1.3_1, units: false, measurement: _instrumentmetrics }
