# CH-DAV
# 15_meteo_snowheight


DAV15-RAW-ICOS-DAT-1MIN-201911050000:
  # ICOS format
  # First file: CH-Dav_BM_20191105_L01_F06.dat (the very first CH-Dav_BM_*_L01_F06.dat file)
  # Last file:  CH-Dav_BM_20211118_L01_F06.dat
  filetype_valid_from: 2019-11-05 00:00:00
  filetype_valid_to: 2021-11-18 00:00:00
  filetype_id: CH-Dav_BM_*_L01_F06.dat
  filetype_dateparser: CH-Dav_BM_%Y%m%d_L01_F06.dat
  filetype_gzip: false
  db_bucket: ch-dav_raw
  filegroup: 15_meteo_snowheight
  data_raw_freq: T
  data_skiprows: [ ]
  data_headerrows: [ 0 ]
  data_index_col: 0
  data_parse_dates: [ 0 ]
  data_date_parser: '%Y%m%d%H%M%S'
  data_build_timestamp: false
  data_keep_good_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: utf-8
  data_delimiter: ','
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    D_SNOW_1_1_1: { field: D_SNOW_M1_X_1, units: false, measurement: D_SNOW }
    DIAG_SR50AT: { field: DIAG_SR50AT_M1_X_1, units: false, measurement: _instrumentmetrics }
    P_1_1_1: { field: P_1_1_1_X_X_X, units: false, measurement: PREC }
    QUALITY_SR50AT: { field: QUALITY_SR50AT_M1_X_1, units: false, measurement: _instrumentmetrics }
    TA_M1_1.8_1: { field: TA_M1_1.8_1, units: false, measurement: TA }


