# CH-DAV
# 13_meteo_nabel


DAV13-RAW-NABEL-CSV-1MIN-201901010000:
  # NABEL format
  # First file: DAV_Meteo_NABEL_190101.CSV (the very first DAV_Meteo_NABEL_*.CSV that is ingested to db)
  # Last file:  *currently running*
  # The very first file is DAV_Meteo_NABEL_181004.CSV, but for 2018 we are using
  #   the 10MIN data.
  # **This file has ANSI encoding**
  #   This encoding is used by default in the legacy components
  #   of Microsoft Windows.
  #   To read this file in Linux, we use data_encoding='cp1252',
  #   which is the same as 'windows-1252'. 'cp1252' works under
  #   Linux and Windows.
  #   see:
  #     - https://docs.python.org/2/library/codecs.html#python-specific-encodings
  #     - https://en.wikipedia.org/wiki/Windows-1252
  #     - https://stackoverflow.com/questions/2014069/windows-1252-to-utf-8-encoding
  # Has some empty columns that are ignored.
  filetype_valid_from: 2019-01-01 00:00:00
  filetype_valid_to: 2099-12-31 23:59:59
  filetype_id: DAV_Meteo_NABEL_*.CSV
  filetype_dateparser: DAV_Meteo_NABEL_%y%m%d.CSV
  filetype_gzip: false
  filegroup: 13_meteo_nabel
  data_raw_freq: T
  data_skiprows: [ 0, 3 ]
  data_headerrows: [ 0, 1 ]
  data_index_col: 0
  data_parse_dates: [ 0 ]
  data_date_parser: '%d.%m.%Y %H:%M'
  data_build_timestamp: false
  data_keep_good_rows: false
  data_remove_bad_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: cp1252
  data_delimiter: ';'
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    TEMP: { field: TA_NABEL_T1_35_1, gain: 1, units: false, measurement: TA }
    FEUCHT: { field: RH_NABEL_T1_35_1, gain: 1, units: false, measurement: RH }
    STRGLO: { field: SW_IN_NABEL_T1_35_1, gain: 1, units: false, measurement: SW }
    REGEN: { field: PREC_TOT_NABEL_T1_20_1, gain: 1, units: false, measurement: PREC }
    Reg_Menge: { field: PREC_CUM_NABEL_T1_20_1, gain: 1, units: false, measurement: PREC }


