# CH-DAV
# 17_meteo_profile


DAV17-RAW-ICOS-PRF-DAT-10S-20180711:
  # ICOS format
  # First file: CH-Dav_BM_20180711_L01_F02.dat (the very first CH-Dav_BM_*_L01_F02.dat file)
  # Last file:  *currently running*
  filetype_valid_from: 2018-07-11 00:00:00
  filetype_valid_to: 2099-12-31 23:59:59
  filetype_id: CH-Dav_BM_*_L01_F02.dat
  filetype_dateparser: CH-Dav_BM_%Y%m%d_L01_F02.dat
  filetype_gzip: false
  db_bucket: ch-dav_raw
  filegroup: 17_meteo_profile
  data_raw_freq: 10S
  data_skiprows: [ ]
  data_headerrows: [ 0 ]
  data_index_col: 0
  data_parse_dates: [ 0 ]
  data_date_parser: '%Y%m%d%H%M%S'
  data_build_timestamp: false
  data_keep_good_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: utf-8
  data_delimiter: ','
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    PA_1_1_1: { field: PA_PRF_X_X_X, units: hPa, measurement: PA }
    RH_1_1_1: { field: RH_PRF_T1_1_1, units: "%", measurement: RH }
    RH_1_2_1: { field: RH_PRF_T1_2_1, units: "%", measurement: RH }
    RH_1_3_1: { field: RH_PRF_T1_10_1, units: "%", measurement: RH }
    RH_1_4_1: { field: RH_PRF_T1_20_1, units: "%", measurement: RH }
    RH_1_5_1: { field: RH_PRF_T1_25_1, units: "%", measurement: RH }
    RH_1_6_1: { field: RH_PRF_T1_35_1, units: "%", measurement: RH }
    TA_1_1_1: { field: TA_PRF_T1_1_1, units: degC, measurement: TA }
    TA_1_2_1: { field: TA_PRF_T1_2_1, units: degC, measurement: TA }
    TA_1_3_1: { field: TA_PRF_T1_10_1, units: degC, measurement: TA }
    TA_1_4_1: { field: TA_PRF_T1_20_1, units: degC, measurement: TA }
    TA_1_5_1: { field: TA_PRF_T1_25_1, units: degC, measurement: TA }
    TA_1_6_1: { field: TA_PRF_T1_35_1, units: degC, measurement: TA }
    WD_1_1_1: { field: WD_PRF_T1_1_1, units: deg, measurement: WD }
    WD_1_2_1: { field: WD_PRF_T1_2_1, units: deg, measurement: WD }
    WD_1_3_1: { field: WD_PRF_T1_10_1, units: deg, measurement: WD }
    WD_1_4_1: { field: WD_PRF_T1_20_1, units: deg, measurement: WD }
    WD_1_5_1: { field: WD_PRF_T1_25_1, units: deg, measurement: WD }
    WS_1_1_1: { field: WS_PRF_T1_1_1, units: m s-1, measurement: WS }
    WS_1_2_1: { field: WS_PRF_T1_2_1, units: m s-1, measurement: WS }
    WS_1_3_1: { field: WS_PRF_T1_10_1, units: m s-1, measurement: WS }
    WS_1_4_1: { field: WS_PRF_T1_20_1, units: m s-1, measurement: WS }
    WS_1_5_1: { field: WS_PRF_T1_25_1, units: m s-1, measurement: WS }
