# CH-DAV
# 12_meteo_forestfloor


DAV12-RAW-FF3-TOA5-DAT-TBL1-1MIN-202110221627:
  # TOA5
  # First file: CH-DAV_iDL_FF3_0_1_TBL1_2021_10_22-1627.dat
  # Last file:  *currently running*
  # Added SoilVUE variables, additional depths (5, 10, 20, 30, 40 and 50 cm), replicates
  # First file has slight naming inconsistency b/c it uses a dash before time at the end
  # --> therefore two patterns for filetype_dateparser
  filetype_valid_from: 2021-10-22 16:27:00
  filetype_valid_to: 2099-12-31 23:59:59
  filetype_id: CH-DAV_iDL_FF3_0_1_TBL1_*.dat
  filetype_dateparser: ['CH-DAV_iDL_FF3_0_1_TBL1_%Y_%m_%d-%H%M.dat', 'CH-DAV_iDL_FF3_0_1_TBL1_%Y_%m_%d_%H%M.dat']
  filetype_gzip: false
  filegroup: 12_meteo_forestfloor
  data_raw_freq: T
  data_skiprows: [ 0, 3 ]
  data_headerrows: [ 0, 1 ]
  data_index_col: 0
  data_parse_dates: [ 0 ]
  data_date_parser: '%Y-%m-%d %H:%M:%S'
  data_build_timestamp: false
  data_keep_good_rows: false
  data_remove_bad_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: utf-8
  data_delimiter: ','
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    DNTP_LOGGER_FF3_0_1: { field: DNTP_LOGGER_FF3_0_1, units: false, gain: 1, measurement: _instrumentmetrics }
    FLAG_G_ISCAL_ETH_3_1_1: { field: FLAG_G_ISCAL_ETH_FF3_0.05_1, units: false, gain: 1, measurement: _instrumentmetrics }
    G_3_1_1_Avg: { field: G_FF3_0.05_1, units: false, gain: 1, measurement: G }
    G_3_1_1_Std: { field: G_SD_FF3_0.05_1, units: false, gain: 1, measurement: _SD }
    G_ISCAL_3_1_1: { field: G_ISCAL_FF3_0.05_1, units: false, gain: 1, measurement: _instrumentmetrics }
    G_IU_3_1_1_Avg: { field: G_IU_FF3_0.05_1, units: false, gain: 1, measurement: _RAW }
    G_SF_3_1_1: { field: G_SF_FF3_0.05_1, units: false, gain: 1, measurement: _instrumentmetrics }
    RECORD: { field: RECORD_FF3_0_1, units: false, gain: 1, measurement: _instrumentmetrics }
    SDP_FF3_0x05_1_Avg: { field: SDP_FF3_0.05_1, units: false, gain: 1, measurement: SDP }
    SDP_FF3_0x10_1_Avg: { field: SDP_FF3_0.10_1, units: false, gain: 1, measurement: SDP }
    SDP_FF3_0x20_1_Avg: { field: SDP_FF3_0.20_1, units: false, gain: 1, measurement: SDP }
    SDP_FF3_0x30_1_Avg: { field: SDP_FF3_0.30_1, units: false, gain: 1, measurement: SDP }
    SDP_FF3_0x40_1_Avg: { field: SDP_FF3_0.40_1, units: false, gain: 1, measurement: SDP }
    SDP_FF3_0x50_1_Avg: { field: SDP_FF3_0.50_1, units: false, gain: 1, measurement: SDP }
    SEC_FF3_0x05_1_Avg: { field: SEC_FF3_0.05_1, units: false, gain: 1, measurement: SDP }
    SEC_FF3_0x10_1_Avg: { field: SEC_FF3_0.10_1, units: false, gain: 1, measurement: SDP }
    SEC_FF3_0x20_1_Avg: { field: SEC_FF3_0.20_1, units: false, gain: 1, measurement: SDP }
    SEC_FF3_0x30_1_Avg: { field: SEC_FF3_0.30_1, units: false, gain: 1, measurement: SDP }
    SEC_FF3_0x40_1_Avg: { field: SEC_FF3_0.40_1, units: false, gain: 1, measurement: SDP }
    SEC_FF3_0x50_1_Avg: { field: SEC_FF3_0.50_1, units: false, gain: 1, measurement: SDP }
    SV_LOGGER_FF3_0_1: { field: SV_LOGGER_FF3_0_1, units: false, gain: 1, measurement: _instrumentmetrics }
    SWC_3_1_1_Avg: { field: SWC_FF3_0.05_1, units: false, gain: 1, measurement: SWC }
    SWC_3_1_1_Std: { field: SWC_SD_FF3_0.05_1, units: false, gain: 1, measurement: _SD }
    SWC_3_1_2_Avg: { field: SWC_FF3_0.05_2, units: false, gain: 1, measurement: SWC }
    SWC_3_1_2_Std: { field: SWC_SD_FF3_0.05_2, units: false, gain: 1, measurement: _SD }
    SWC_3_1_3_Avg: { field: SWC_FF3_0.05_3, units: false, gain: 1, measurement: SWC }
    SWC_3_2_1_Avg: { field: SWC_FF3_0.10_1, units: false, gain: 1, measurement: SWC }
    SWC_3_2_1_Std: { field: SWC_SD_FF3_0.10_1, units: false, gain: 1, measurement: _SD }
    SWC_3_2_2_Avg: { field: SWC_FF3_0.10_2, units: false, gain: 1, measurement: SWC }
    SWC_3_3_1_Avg: { field: SWC_FF3_0.21_1, units: false, gain: 1, measurement: SWC }
    SWC_3_3_1_Std: { field: SWC_SD_FF3_0.21_1, units: false, gain: 1, measurement: _SD }
    SWC_3_3_2_Avg: { field: SWC_FF3_0.20_2, units: false, gain: 1, measurement: SWC }
    SWC_3_4_1_Avg: { field: SWC_FF3_0.30_1, units: false, gain: 1, measurement: SWC }
    SWC_3_5_1_Avg: { field: SWC_FF3_0.40_1, units: false, gain: 1, measurement: SWC }
    SWC_3_6_1_Avg: { field: SWC_FF3_0.52_1, units: false, gain: 1, measurement: SWC }
    SWC_3_6_1_Std: { field: SWC_SD_FF3_0.52_1, units: false, gain: 1, measurement: _SD }
    SWC_3_6_2_Avg: { field: SWC_FF3_0.50_2, units: false, gain: 1, measurement: SWC }
    SWC_3_7_1_Avg: { field: SWC_FF3_0.68_1, units: false, gain: 1, measurement: SWC }
    SWC_3_7_1_Std: { field: SWC_SD_FF3_0.68_1, units: false, gain: 1, measurement: _SD }
    SWC_IU_3_1_1_Avg: { field: SWC_IU_FF3_0.05_1, units: false, gain: 1, measurement: _RAW }
    SWC_IU_3_1_2_Avg: { field: SWC_IU_FF3_0.05_2, units: false, gain: 1, measurement: _RAW }
    SWC_IU_3_2_1_Avg: { field: SWC_IU_FF3_0.10_1, units: false, gain: 1, measurement: _RAW }
    SWC_IU_3_3_1_Avg: { field: SWC_IU_FF3_0.21_1, units: false, gain: 1, measurement: _RAW }
    SWC_IU_3_6_1_Avg: { field: SWC_IU_FF3_0.52_1, units: false, gain: 1, measurement: _RAW }
    SWC_IU_3_7_1_Avg: { field: SWC_IU_FF3_0.68_1, units: false, gain: 1, measurement: _RAW }
    T_LOGGER_FF3_0_1: { field: T_LOGGER_FF3_0_1, units: false, gain: 1, measurement: _instrumentmetrics }
    TS_3_1_1_Avg: { field: TS_FF3_0.03_1, units: false, gain: 1, measurement: TS }
    TS_3_1_1_Std: { field: TS_SD_FF3_0.03_1, units: false, gain: 1, measurement: _SD }
    TS_3_2_1_Avg: { field: TS_FF3_0.05_1, units: false, gain: 1, measurement: TS }
    TS_3_2_1_Std: { field: TS_SD_FF3_0.05_1, units: false, gain: 1, measurement: _SD }
    TS_3_2_2_Avg: { field: TS_FF3_0.05_2, units: false, gain: 1, measurement: TS }
    TS_3_2_2_Std: { field: TS_SD_FF3_0.05_2, units: false, gain: 1, measurement: _SD }
    TS_3_2_3_Avg: { field: TS_FF3_0.05_3, units: false, gain: 1, measurement: TS }
    TS_3_3_1_Avg: { field: TS_FF3_0.11_1, units: false, gain: 1, measurement: TS }
    TS_3_3_1_Std: { field: TS_SD_FF3_0.11_1, units: false, gain: 1, measurement: _SD }
    TS_3_3_2_Avg: { field: TS_FF3_0.10_2, units: false, gain: 1, measurement: TS }
    TS_3_4_1_Avg: { field: TS_FF3_0.20_1, units: false, gain: 1, measurement: TS }
    TS_3_4_1_Std: { field: TS_SD_FF3_0.20_1, units: false, gain: 1, measurement: _SD }
    TS_3_4_2_Avg: { field: TS_FF3_0.20_2, units: false, gain: 1, measurement: TS }
    TS_3_5_1_Avg: { field: TS_FF3_0.30_1, units: false, gain: 1, measurement: TS }
    TS_3_6_1_Avg: { field: TS_FF3_0.40_1, units: false, gain: 1, measurement: TS }
    TS_3_7_1_Avg: { field: TS_FF3_0.50_1, units: false, gain: 1, measurement: TS }
    TS_3_7_1_Std: { field: TS_SD_FF3_0.50_1, units: false, gain: 1, measurement: _SD }
    TS_3_7_2_Avg: { field: TS_FF3_0.50_2, units: false, gain: 1, measurement: TS }
    TS_3_8_1_Avg: { field: TS_FF3_0.60_1, units: false, gain: 1, measurement: TS }
    TS_3_8_1_Std: { field: TS_SD_FF3_0.60_1, units: false, gain: 1, measurement: _SD }
    TS_IU_3_1_1_Avg: { field: TS_IU_FF3_0.03_1, units: false, gain: 1, measurement: _RAW }
    TS_IU_3_2_1_Avg: { field: TS_IU_FF3_0.05_1, units: false, gain: 1, measurement: _RAW }
    TS_IU_3_2_2_Avg: { field: TS_IU_FF3_0.05_2, units: false, gain: 1, measurement: _RAW }
    TS_IU_3_3_1_Avg: { field: TS_IU_FF3_0.11_1, units: false, gain: 1, measurement: _RAW }
    TS_IU_3_4_1_Avg: { field: TS_IU_FF3_0.20_1, units: false, gain: 1, measurement: _RAW }
    TS_IU_3_7_1_Avg: { field: TS_IU_FF3_0.50_1, units: false, gain: 1, measurement: _RAW }
    TS_IU_3_8_1_Avg: { field: TS_IU_FF3_0.60_1, units: false, gain: 1, measurement: _RAW }


