# CH-DAV
# 17_meteo_profile


DAV17-RAW-TOA5-PRF-DAT-AUX-1MIN-202112140000:
  # TOA5 format
  # First file: CH-DAV_meteo-profile-aux_20211214.dat (the very first CH-DAV_meteo-profile-aux_*.dat file)
  # Last file:  *currently running*
  filetype_valid_from: 2021-12-14 00:00:00
  filetype_valid_to: 2099-12-31 23:59:59
  filetype_id: CH-DAV_meteo-profile-aux_*.dat
  filetype_dateparser: CH-DAV_meteo-profile-aux_%Y%m%d.dat
  filetype_gzip: false
  filegroup: 17_meteo_profile
  data_raw_freq: T
  data_skiprows: [ 0, 3 ]
  data_headerrows: [ 0, 1 ]
  data_index_col: 0
  data_parse_dates: [ 0 ]
  data_date_parser: '%Y-%m-%d %H:%M:%S'
  data_build_timestamp: false
  data_keep_good_rows: false
  data_remove_bad_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: utf-8
  data_delimiter: ','
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    ERROR_iWIND_T1_1_1: { field: ERROR_iWIND_T1_1_1, units: false, measurement: _instrumentmetrics }
    ERROR_iWIND_T1_2_1: { field: ERROR_iWIND_T1_2_1, units: false, measurement: _instrumentmetrics }
    ERROR_iWIND_T1_10_1: { field: ERROR_iWIND_T1_10_1, units: false, measurement: _instrumentmetrics }
    ERROR_iWIND_T1_20_1: { field: ERROR_iWIND_T1_20_1, units: false, measurement: _instrumentmetrics }
    ERROR_iWIND_T1_25_1: { field: ERROR_iWIND_T1_25_1, units: false, measurement: _instrumentmetrics }
    ERROR_iWIND_T1_35_1: { field: ERROR_iWIND_T1_35_1, units: false, measurement: _instrumentmetrics }
    STATUS_iWIND_T1_1_1: { field: STATUS_iWIND_T1_1_1, units: false, measurement: _instrumentmetrics }
    STATUS_iWIND_T1_2_1: { field: STATUS_iWIND_T1_2_1, units: false, measurement: _instrumentmetrics }
    STATUS_iWIND_T1_10_1: { field: STATUS_iWIND_T1_10_1, units: false, measurement: _instrumentmetrics }
    STATUS_iWIND_T1_20_1: { field: STATUS_iWIND_T1_20_1, units: false, measurement: _instrumentmetrics }
    STATUS_iWIND_T1_25_1: { field: STATUS_iWIND_T1_25_1, units: false, measurement: _instrumentmetrics }
    STATUS_iWIND_T1_35_1: { field: STATUS_iWIND_T1_35_1, units: false, measurement: _instrumentmetrics }
    T_ACOUSTIC_T1_1_1: { field: T_ACOUSTIC_T1_1_1, units: false, measurement: _instrumentmetrics }
    T_ACOUSTIC_T1_2_1: { field: T_ACOUSTIC_T1_2_1, units: false, measurement: _instrumentmetrics }
    T_ACOUSTIC_T1_10_1: { field: T_ACOUSTIC_T1_10_1, units: false, measurement: _instrumentmetrics }
    T_ACOUSTIC_T1_20_1: { field: T_ACOUSTIC_T1_20_1, units: false, measurement: _instrumentmetrics }
    T_ACOUSTIC_T1_25_1: { field: T_ACOUSTIC_T1_25_1, units: false, measurement: _instrumentmetrics }
    T_ACOUSTIC_T1_35_1: { field: T_ACOUSTIC_T1_35_1, units: false, measurement: _instrumentmetrics }
    T_iWIND_T1_1_1: { field: T_iWIND_T1_1_1, units: false, measurement: _instrumentmetrics }
    T_iWIND_T1_2_1: { field: T_iWIND_T1_2_1, units: false, measurement: _instrumentmetrics }
    T_iWIND_T1_10_1: { field: T_iWIND_T1_10_1, units: false, measurement: _instrumentmetrics }
    T_iWIND_T1_20_1: { field: T_iWIND_T1_20_1, units: false, measurement: _instrumentmetrics }
    T_iWIND_T1_25_1: { field: T_iWIND_T1_25_1, units: false, measurement: _instrumentmetrics }
    T_iWIND_T1_35_1: { field: T_iWIND_T1_35_1, units: false, measurement: _instrumentmetrics }

