# CH-DAV
# 17_meteo_profile

#   NABEL profile measurements, P2 = profile 2 (with CO2)
#
#   Complete year 2006 in one file
#
#   Basically the same filetype as DAV17-RAW-NABEL-PRF-SSV-DAT-P2-5MIN-200001010000.yaml,
#   but only for 2006. In that year the column order changed, and since for this
#   filetype the correct column order needs to be provided in the settings here,
#   a separate settings file (this here) is necessary.
#
#   For more info about this filetype see DAV17-RAW-NABEL-PRF-SSV-DAT-P2-5MIN-200001010000.yaml

DAV17-RAW-NABEL-PRF-SSV-DAT-P2-5MIN-200601010000:
  # SSV: space-separated files
  # First file: Davos_P2_2006-05Min.dat
  # Last file:  Davos_P2_2006-05Min.dat (same as first file)
  filetype_valid_from: 2006-01-01 00:00:00
  filetype_valid_to: 2006-01-01 00:00:00
  filetype_id: Davos_P2_*-05Min.dat
  filetype_dateparser: Davos_P2_%Y-05Min.dat
  filetype_gzip: false
  filegroup: 12_meteo_forestfloor
  data_raw_freq: 5T
  data_skiprows: [ 0, 1 ]
#  data_skiprows: [ 0 ]
  data_headerrows: 0
#  data_headerrows: [ 0 ]
  data_index_col: 0
  data_parse_dates: [ 0 ]
  data_date_parser: '%Y%m%d%H%M'
  data_build_timestamp: false
  data_keep_good_rows: false
  # If "-999.9000-999.9000-999.9000-999.9000-999.9000" (str) is in the first column (index 0),
  # the data row is bad and removed
  data_remove_bad_rows: [ 0, "-999.9000-999.9000-999.9000-999.9000-999.9000"]
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: utf-8
  data_delimiter: '\s+'
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    # First col also counts, but is ignored
    TIMESTAMP: this column is necessary but ignored!
    CO2ABS35: { field: CO2_PRF_T1_35_1, units: ppm, gain: 1, measurement: CO2 }
    CO2ABS25: { field: CO2_PRF_T1_25_1, units: ppm, gain: 1, measurement: CO2 }
    CO2ABS20: { field: CO2_PRF_T1_20_1, units: ppm, gain: 1, measurement: CO2 }
    CO2ABS10: { field: CO2_PRF_T1_10_1, units: ppm, gain: 1, measurement: CO2 }
    CO2ABS02: { field: CO2_PRF_T1_2_1, units: ppm, gain: 1, measurement: CO2 }
    TEMPMK3: { field: TEMPMK3_X_X_X, units: false, gain: 1, measurement: XXX }
    BATTV03: { field: BATTV03_X_X_X, units: V, gain: 1, measurement: XXX }
    TEMPCR10: { field: TEMPCR10_X_X_X, units: false, gain: 1, measurement: XXX }
