# CH-AWS
# 15_meteo_snowheight


AWS15-RAW-TOA5-DAT-1MIN-201911130000:
  # TOA5 (but with empty unit row)
  # First file: CH-AWS_snowheight_20191113.dat
  # Last file:  *currently running*
  # Due to the empty unit row more lines have to be skipped than for regular TOA5 files,
  #   i.e. in the setting 'data_skiprows' the 2nd row has also to be skipped [ 0, 2, 3 ].
  #   This is necessary because it seems that 'data_headerrows' cannot handle empty unit
  #   rows.
  filetype_valid_from: 2019-11-13 00:00:00
  filetype_valid_to: 2099-12-31 23:59:59
  filetype_id: CH-AWS_snowheight_*.dat
  filetype_dateparser: CH-AWS_snowheight_%Y%m%d.dat
  filetype_gzip: false
  filegroup: 15_meteo_snowheight
  data_raw_freq: T
  data_skiprows: [ 0, 2, 3 ]  # Exception to other TOA5 files
  data_headerrows: [ 0 ]  # Exception to other TOA5 files
  data_index_col: 0
  data_parse_dates: [ 0 ]
  data_date_parser: '%Y-%m-%d %H:%M:%S'
  data_build_timestamp: false
  data_keep_good_rows: false
  data_remove_bad_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: utf-8
  data_delimiter: ','
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    D_SNOW_1_1_1: { field: D_SNOW_GF0_0_1, units: false, measurement: D_SNOW }
    D_SNOW_GF0_0_1: { field: D_SNOW_GF0_0_1, units: false, measurement: D_SNOW }
    DIAG_SR50AT: { field: DIAG_SR50AT_X_X_X, units: false, measurement: _instrumentmetrics }
    DIST_1: { field: DIST_1_X_X_X, units: false, measurement: D_SNOW }
    DIST_2: { field: DIST_2_X_X_X, units: false, measurement: D_SNOW }
    DIST_3: { field: DIST_3_X_X_X, units: false, measurement: D_SNOW }
    ERROR_1: { field: ERROR_1_X_X_X, units: false, measurement: _instrumentmetrics }
    ERROR_2: { field: ERROR_2_X_X_X, units: false, measurement: _instrumentmetrics }
    ERROR_3: { field: ERROR_3_X_X_X, units: false, measurement: _instrumentmetrics }
    QUALITY_SR50AT: { field: QUALITY_SR50AT_X_X_X, units: false, measurement: _instrumentmetrics }
    TA_M1_1.8_1: { field: TA_M1_1.8_1, units: false, measurement: TA }
    TA_M3_2.5_1: { field: TA_M3_2.5_1, units: false, measurement: TA }

