# CH-FRU
# 10_meteo


FRU10-RAW-TOA5-DAT-TBL1-1MIN-201711201643:
  # TOA5
  # First file: CH-FRU_iDL_BOX1_0_1_TBL1_20171120-1643.dat (the very first CH-FRU_iDL_BOX1_0_1_TBL1_*.dat file)
  # Last file:  *currently running*
  filetype_valid_from: 2017-11-20 16:43:00
  filetype_valid_to: 2099-02-28 11:01:00
  filetype_id: CH-FRU_iDL_BOX1_0_1_TBL1_*.dat
  filetype_dateparser: CH-FRU_iDL_BOX1_0_1_TBL1_%Y%m%d-%H%M.dat
  filetype_gzip: false
  db_bucket: ch-fru_raw
  filegroup: 10_meteo
  data_raw_freq: T
  data_skiprows: [ 0, 3 ]
  data_headerrows: [ 0, 1 ]
  data_index_col: 0
  data_parse_dates: [ 0 ]
  data_date_parser: '%Y-%m-%d %H:%M:%S'
  data_build_timestamp: false
  data_keep_good_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: utf-8
  data_delimiter: ','
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    BV_iDL_BOX1_0_1_Avg: { field: BV_iDL_BOX1_0_1, units: false, measurement: _instrumentmetrics }
    BV_iDL_BOX1_0_1_Std: { field: BV_iDL_SD_BOX1_0_1, units: false, measurement: _instrumentmetrics }
    DNTP_iDL_BOX1_0_1: { field: DNTP_iDL_BOX1_0_1, units: false, measurement: _instrumentmetrics }
    G_GF1_0x06_1_Avg: { field: G_GF1_0.06_1, units: false, measurement: G }
    G_GF1_0x06_1_Std: { field: G_GF1_SD_0.06_1, units: false, measurement: _SD }
    G_GF1_0x06_2_Avg: { field: G_GF1_0.06_2, units: false, measurement: G }
    G_GF1_0x06_2_Std: { field: G_GF1_SD_0.06_2, units: false, measurement: _SD }
    HEAT_HS50: { field: HEAT_HS50_X_X_X, units: false, measurement: _instrumentmetrics }
    LW_IN_RAW_T1_1_1_Avg: { field: LW_IN_RAW_T1_1_1, units: false, measurement: _RAW }
    LW_IN_T1_1_1_Avg: { field: LW_IN_T1_1_1, units: false, measurement: LW }
    LW_IN_T1_1_1_Std: { field: LW_IN_SD_T1_1_1, units: false, measurement: _SD }
    LW_OUT_RAW_T1_1_1_Avg: { field: LW_OUT_RAW_T1_1_1, units: false, measurement: _RAW }
    LW_OUT_T1_1_1_Avg: { field: LW_OUT_T1_1_1, units: false, measurement: LW }
    LW_OUT_T1_1_1_Std: { field: LW_OUT_SD_T1_1_1, units: false, measurement: _SD }
    PPFD_IN_T1_2_1_Avg: { field: PPFD_IN_T1_2_1, units: false, measurement: PPFD }
    PPFD_IN_T1_2_1_Std: { field: PPFD_IN_SD_T1_2_1, units: false, measurement: _SD }
    PPFD_OUT_T1_2_1_Avg: { field: PPFD_OUT_T1_2_1, units: false, measurement: PPFD }
    PPFD_OUT_T1_2_1_Std: { field: PPFD_OUT_SD_T1_2_1, units: false, measurement: _SD }
    PREC_GF1_0x50_1_Std: { field: PREC_SD_GF1_0.50_1, units: false, measurement: _SD }
    PREC_GF1_0x50_1_Tot: { field: PREC_TOT_GF1_0.50_1, units: false, measurement: PREC }
    PREC_T1_0x50_1_Std: { field: PREC_SD_T1_0.50_1, units: false, measurement: _SD }
    PREC_T1_0x50_1_Tot: { field: PREC_TOT_T1_0.50_1, units: false, measurement: PREC }
    RECORD: { field: RECORD_X_X_X, units: false, measurement: _instrumentmetrics }
    RH_T1_2_1_Avg: { field: RH_T1_2_1, units: false, measurement: RH }
    RH_T1_2_1_Std: { field: RH_SD_T1_2_1, units: false, measurement: _SD }
    SDI12_PWR_Max: { field: SDI12_PWR_MAX_X_X_X, units: false, measurement: _instrumentmetrics }
    SDI12_PWR_TMx: { field: SDI12_PWR_TMX_X_X_X, units: false, measurement: _instrumentmetrics }
    SDP_GF1_0x05_1_Avg: { field: SDP_GF1_0.05_1, units: false, measurement: SDP }
    SDP_GF1_0x05_1_Std: { field: SDP_SD_GF1_0.05_1, units: false, measurement: _SD }
    SDP_GF1_0x15_1_Avg: { field: SDP_GF1_0.15_1, units: false, measurement: SDP }
    SDP_GF1_0x15_1_Std: { field: SDP_SD_GF1_0.15_1, units: false, measurement: _SD }
    SDP_GF1_0x25_1_Avg: { field: SDP_GF1_0.25_1, units: false, measurement: SDP }
    SDP_GF1_0x25_1_Std: { field: SDP_SD_GF1_0.25_1, units: false, measurement: _SD }
    SDP_GF1_0x40_1_Avg: { field: SDP_GF1_0.40_1, units: false, measurement: SDP }
    SDP_GF1_0x40_1_Std: { field: SDP_SD_GF1_0.40_1, units: false, measurement: _SD }
    SDP_GF1_0x95_1_Avg: { field: SDP_GF1_0.95_1, units: false, measurement: SDP }
    SDP_GF1_0x95_1_Std: { field: SDP_SD_GF1_0.95_1, units: false, measurement: _SD }
    SV_iDL_BOX1_0_1_Avg: { field: SV_iDL_BOX1_0_1, units: false, measurement: _instrumentmetrics }
    SV_iDL_BOX1_0_1_Std: { field: SV_iDL_SD_BOX1_0_1, units: false, measurement: _instrumentmetrics }
    SW_IN_T1_1_1_Avg: { field: SW_IN_T1_1_1, units: false, measurement: SW }
    SW_IN_T1_1_1_Std: { field: SW_IN_SD_T1_1_1, units: false, measurement: _SD }
    SW_OUT_T1_1_1_Avg: { field: SW_OUT_T1_1_1, units: false, measurement: SW }
    SW_OUT_T1_1_1_Std: { field: SW_OUT_SD_T1_1_1, units: false, measurement: _SD }
    SWC_GF1_0x05_1_Avg: { field: SWC_GF1_0.05_1, units: false, measurement: SWC }
    SWC_GF1_0x05_1_Std: { field: SWC_SD_GF1_0.05_1, units: false, measurement: _SD }
    SWC_GF1_0x15_1_Avg: { field: SWC_GF1_0.15_1, units: false, measurement: SWC }
    SWC_GF1_0x15_1_Std: { field: SWC_SD_GF1_0.15_1, units: false, measurement: _SD }
    SWC_GF1_0x25_1_Avg: { field: SWC_GF1_0.25_1, units: false, measurement: SWC }
    SWC_GF1_0x25_1_Std: { field: SWC_SD_GF1_0.25_1, units: false, measurement: _SD }
    SWC_GF1_0x40_1_Avg: { field: SWC_GF1_0.40_1, units: false, measurement: SWC }
    SWC_GF1_0x40_1_Std: { field: SWC_SD_GF1_0.40_1, units: false, measurement: _SD }
    SWC_GF1_0x95_1_Avg: { field: SWC_GF1_0.95_1, units: false, measurement: SWC }
    SWC_GF1_0x95_1_Std: { field: SWC_SD_GF1_0.95_1, units: false, measurement: _SD }
    SWC_GF2_1x00_1_Avg: { field: SWC_GF2_1.00_1, units: false, measurement: SWC }
    SWC_GF2_1x00_1_Std: { field: SWC_SD_GF2_1.00_1, units: false, measurement: _SD }
    SWC_GF2_0x10_1_Avg: { field: SWC_GF2_0.10_1, units: false, measurement: SWC }
    SWC_GF2_0x10_1_Std: { field: SWC_SD_GF2_0.10_1, units: false, measurement: _SD }
    SWC_GF2_0x20_1_Avg: { field: SWC_GF2_0.20_1, units: false, measurement: SWC }
    SWC_GF2_0x20_1_Std: { field: SWC_SD_GF2_0.20_1, units: false, measurement: _SD }
    SWC_GF2_0x30_1_Avg: { field: SWC_GF2_0.30_1, units: false, measurement: SWC }
    SWC_GF2_0x30_1_Std: { field: SWC_SD_GF2_0.30_1, units: false, measurement: _SD }
    SWC_GF2_0x40_1_Avg: { field: SWC_GF2_0.40_1, units: false, measurement: SWC }
    SWC_GF2_0x40_1_Std: { field: SWC_SD_GF2_0.40_1, units: false, measurement: _SD }
    SWC_GF2_0x60_1_Avg: { field: SWC_GF2_0.60_1, units: false, measurement: SWC }
    SWC_GF2_0x60_1_Std: { field: SWC_SD_GF2_0.60_1, units: false, measurement: _SD }
    T_BOX1_0x40_1_Avg: { field: T_BOX1_0.40_1, units: false, measurement: _instrumentmetrics }
    T_BOX1_0x40_1_Std: { field: T_BOX1_SD_0.40_1, units: false, measurement: _instrumentmetrics }
    T_iDL_BOX1_0_1_Avg: { field: T_iDL_BOX1_0_1, units: false, measurement: _instrumentmetrics }
    T_iDL_BOX1_0_1_Std: { field: T_iDL_SD_BOX1_0_1, units: false, measurement: _instrumentmetrics }
    T_RAD_T1_1_1_Avg: { field: T_RAD_T1_1_1, units: false, measurement: _instrumentmetrics }
    T_RAD_T1_1_1_Std: { field: T_RAD_SD_T1_1_1, units: false, measurement: _instrumentmetrics }
    TA_T1_2_1_Avg: { field: TA_T1_2_1, units: false, measurement: TA }
    TA_T1_2_1_Std: { field: TA_SD_T1_2_1, units: false, measurement: _SD }
    TS_GF1_1x00_2_Avg: { field: TS_GF1_1.00_2, units: false, measurement: TS }
    TS_GF1_1x00_2_Std: { field: TS_SD_GF1_1.00_2, units: false, measurement: _SD }
    TS_GF1_0x01_1_Avg: { field: TS_GF1_0.01_1, units: false, measurement: TS }
    TS_GF1_0x01_1_Std: { field: TS_SD_GF1_0.01_1, units: false, measurement: _SD }
    TS_GF1_0x02_1_Avg: { field: TS_GF1_0.02_1, units: false, measurement: TS }
    TS_GF1_0x02_1_Std: { field: TS_SD_GF1_0.02_1, units: false, measurement: _SD }
    TS_GF1_0x02_2_Avg: { field: TS_GF1_0.02_2, units: false, measurement: TS }
    TS_GF1_0x02_2_Std: { field: TS_SD_GF1_0.02_2, units: false, measurement: _SD }
    TS_GF1_0x04_1_Avg: { field: TS_GF1_0.04_1, units: false, measurement: TS }
    TS_GF1_0x04_1_Std: { field: TS_SD_GF1_0.04_1, units: false, measurement: _SD }
    TS_GF1_0x07_1_Avg: { field: TS_GF1_0.07_1, units: false, measurement: TS }
    TS_GF1_0x07_1_Std: { field: TS_SD_GF1_0.07_1, units: false, measurement: _SD }
    TS_GF1_0x10_1_Avg: { field: TS_GF1_0.10_1, units: false, measurement: TS }
    TS_GF1_0x10_1_Std: { field: TS_SD_GF1_0.10_1, units: false, measurement: _SD }
    TS_GF1_0x10_2_Avg: { field: TS_GF1_0.10_2, units: false, measurement: TS }
    TS_GF1_0x10_2_Std: { field: TS_SD_GF1_0.10_2, units: false, measurement: _SD }
    TS_GF1_0x15_1_Avg: { field: TS_GF1_0.15_1, units: false, measurement: TS }
    TS_GF1_0x15_1_Std: { field: TS_SD_GF1_0.15_1, units: false, measurement: _SD }
    TS_GF1_0x20_2_Avg: { field: TS_GF1_0.20_2, units: false, measurement: TS }
    TS_GF1_0x20_2_Std: { field: TS_SD_GF1_0.20_2, units: false, measurement: _SD }
    TS_GF1_0x25_1_Avg: { field: TS_GF1_0.25_1, units: false, measurement: TS }
    TS_GF1_0x25_1_Std: { field: TS_SD_GF1_0.25_1, units: false, measurement: _SD }
    TS_GF1_0x30_2_Avg: { field: TS_GF1_0.30_2, units: false, measurement: TS }
    TS_GF1_0x30_2_Std: { field: TS_SD_GF1_0.30_2, units: false, measurement: _SD }
    TS_GF1_0x40_1_Avg: { field: TS_GF1_0.40_1, units: false, measurement: TS }
    TS_GF1_0x40_1_Std: { field: TS_SD_GF1_0.40_1, units: false, measurement: _SD }
    TS_GF1_0x50_2_Avg: { field: TS_GF1_0.50_2, units: false, measurement: TS }
    TS_GF1_0x50_2_Std: { field: TS_SD_GF1_0.50_2, units: false, measurement: _SD }
    TS_GF1_0x95_1_Avg: { field: TS_GF1_0.95_1, units: false, measurement: TS }
    TS_GF1_0x95_1_Std: { field: TS_SD_GF1_0.95_1, units: false, measurement: _SD }
    TS_GF2_1x00_1_Avg: { field: TS_GF2_1.00_1, units: false, measurement: TS }
    TS_GF2_1x00_1_Std: { field: TS_SD_GF2_1.00_1, units: false, measurement: _SD }
    TS_GF2_0x05_1_Avg: { field: TS_GF2_0.05_1, units: false, measurement: TS }
    TS_GF2_0x05_1_Std: { field: TS_SD_GF2_0.05_1, units: false, measurement: _SD }
    TS_GF2_0x10_1_Avg: { field: TS_GF2_0.10_1, units: false, measurement: TS }
    TS_GF2_0x10_1_Std: { field: TS_SD_GF2_0.10_1, units: false, measurement: _SD }
    TS_GF2_0x20_1_Avg: { field: TS_GF2_0.20_1, units: false, measurement: TS }
    TS_GF2_0x20_1_Std: { field: TS_SD_GF2_0.20_1, units: false, measurement: _SD }
    TS_GF2_0x30_1_Avg: { field: TS_GF2_0.30_1, units: false, measurement: TS }
    TS_GF2_0x30_1_Std: { field: TS_SD_GF2_0.30_1, units: false, measurement: _SD }
    TS_GF2_0x50_1_Avg: { field: TS_GF2_0.50_1, units: false, measurement: TS }
    TS_GF2_0x50_1_Std: { field: TS_SD_GF2_0.50_1, units: false, measurement: _SD }
    WD_VANE_T1_2_1_Std: { field: WD_VANE_SD_T1_2_1, units: false, measurement: _SD }
    WS_CUP_T1_2_1_Std: { field: WS_CUP_SD_T1_2_1, units: false, measurement: _SD }
    WS_CUP_T1_2_1_WVc(1): { field: WS_CUP_WVc(1)_T1_2_1, units: false, measurement: WS }
    WS_CUP_T1_2_1_WVc(2): { field: WS_CUP_WVc(2)_T1_2_1, units: false, measurement: WS }
    WS_CUP_T1_2_1_WVc(3): { field: WS_CUP_WVc(3)_T1_2_1, units: false, measurement: WS }
    WS_CUP_T1_2_1_WVc(4): { field: WS_CUP_WVc(4)_T1_2_1, units: false, measurement: WS }











