# CH-FRU
# 10_meteo


FRU10-RAW-TOA5-DAT-TBL2-10MIN-202112161520:
  # TOA5
  # First file: CH-FRU_iDL_BOX1_0_1_TBL2_20211216-1520.dat (the very first CH-FRU_iDL_BOX1_0_1_TBL2_*.dat file)
  # Last file:  *currently running*
  filetype_valid_from: 2021-12-16 15:20:00
  filetype_valid_to: 2099-12-31 23:59:59
  filetype_id: CH-FRU_iDL_BOX1_0_1_TBL2_*.dat
  filetype_dateparser: CH-FRU_iDL_BOX1_0_1_TBL2_%Y%m%d-%H%M.dat
  filetype_gzip: false
  filegroup: 10_meteo
  data_raw_freq: 10T
  data_skiprows: [ 0, 3 ]
  data_headerrows: [ 0, 1 ]
  data_index_col: 0
  data_parse_dates: [ 0 ]
  data_date_parser: '%Y-%m-%d %H:%M:%S'
  data_build_timestamp: false
  data_keep_good_rows: false
  data_remove_bad_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: utf-8
  data_delimiter: ','
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    RECORD: { field: RECORD_X_X_X, units: false, measurement: _instrumentmetrics }
    TS_GF1_1x00_2_Avg: { field: TS_GF1_1.00_2, units: false, measurement: TS }
    TS_GF1_0x05_2_Avg: { field: TS_GF1_0.05_2, units: false, measurement: TS }
    TS_GF1_0x10_2_Avg: { field: TS_GF1_0.10_2, units: false, measurement: TS }
    TS_GF1_0x20_2_Avg: { field: TS_GF1_0.20_2, units: false, measurement: TS }
    TS_GF1_0x30_2_Avg: { field: TS_GF1_0.30_2, units: false, measurement: TS }
    TS_GF1_0x40_2_Avg: { field: TS_GF1_0.40_2, units: false, measurement: TS }
    TS_GF1_0x50_2_Avg: { field: TS_GF1_0.50_2, units: false, measurement: TS }
    TS_GF1_0x60_2_Avg: { field: TS_GF1_0.60_2, units: false, measurement: TS }
    TS_GF1_0x75_2_Avg: { field: TS_GF1_0.75_2, units: false, measurement: TS }
    SDP_GF1_1x00_2_Avg: { field: SDP_GF1_1.00_2, units: false, measurement: SDP }
    SDP_GF1_0x05_2_Avg: { field: SDP_GF1_0.05_2, units: false, measurement: SDP }
    SDP_GF1_0x10_2_Avg: { field: SDP_GF1_0.10_2, units: false, measurement: SDP }
    SDP_GF1_0x20_2_Avg: { field: SDP_GF1_0.20_2, units: false, measurement: SDP }
    SDP_GF1_0x30_2_Avg: { field: SDP_GF1_0.30_2, units: false, measurement: SDP }
    SDP_GF1_0x40_2_Avg: { field: SDP_GF1_0.40_2, units: false, measurement: SDP }
    SDP_GF1_0x50_2_Avg: { field: SDP_GF1_0.50_2, units: false, measurement: SDP }
    SDP_GF1_0x60_2_Avg: { field: SDP_GF1_0.60_2, units: false, measurement: SDP }
    SDP_GF1_0x75_2_Avg: { field: SDP_GF1_0.75_2, units: false, measurement: SDP }
    SEC_GF1_1x00_2_Avg: { field: SEC_GF1_1.00_2, units: false, measurement: SEC }
    SEC_GF1_0x05_2_Avg: { field: SEC_GF1_0.05_2, units: false, measurement: SEC }
    SEC_GF1_0x10_2_Avg: { field: SEC_GF1_0.10_2, units: false, measurement: SEC }
    SEC_GF1_0x20_2_Avg: { field: SEC_GF1_0.20_2, units: false, measurement: SEC }
    SEC_GF1_0x30_2_Avg: { field: SEC_GF1_0.30_2, units: false, measurement: SEC }
    SEC_GF1_0x40_2_Avg: { field: SEC_GF1_0.40_2, units: false, measurement: SEC }
    SEC_GF1_0x50_2_Avg: { field: SEC_GF1_0.50_2, units: false, measurement: SEC }
    SEC_GF1_0x60_2_Avg: { field: SEC_GF1_0.60_2, units: false, measurement: SEC }
    SEC_GF1_0x75_2_Avg: { field: SEC_GF1_0.75_2, units: false, measurement: SEC }
    SWC_GF1_1x00_2_Avg: { field: SWC_GF1_1.00_2, units: false, measurement: SWC }
    SWC_GF1_0x05_2_Avg: { field: SWC_GF1_0.05_2, units: false, measurement: SWC }
    SWC_GF1_0x10_2_Avg: { field: SWC_GF1_0.10_2, units: false, measurement: SWC }
    SWC_GF1_0x20_2_Avg: { field: SWC_GF1_0.20_2, units: false, measurement: SWC }
    SWC_GF1_0x30_2_Avg: { field: SWC_GF1_0.30_2, units: false, measurement: SWC }
    SWC_GF1_0x40_2_Avg: { field: SWC_GF1_0.40_2, units: false, measurement: SWC }
    SWC_GF1_0x50_2_Avg: { field: SWC_GF1_0.50_2, units: false, measurement: SWC }
    SWC_GF1_0x60_2_Avg: { field: SWC_GF1_0.60_2, units: false, measurement: SWC }
    SWC_GF1_0x75_2_Avg: { field: SWC_GF1_0.75_2, units: false, measurement: SWC }
    TS_GF1_1x00_2_Std: { field: TS_SD_GF1_1.00_2, units: false, measurement: _SD }
    TS_GF1_0x05_2_Std: { field: TS_SD_GF1_0.05_2, units: false, measurement: _SD }
    TS_GF1_0x10_2_Std: { field: TS_SD_GF1_0.10_2, units: false, measurement: _SD }
    TS_GF1_0x20_2_Std: { field: TS_SD_GF1_0.20_2, units: false, measurement: _SD }
    TS_GF1_0x30_2_Std: { field: TS_SD_GF1_0.30_2, units: false, measurement: _SD }
    TS_GF1_0x40_2_Std: { field: TS_SD_GF1_0.40_2, units: false, measurement: _SD }
    TS_GF1_0x50_2_Std: { field: TS_SD_GF1_0.50_2, units: false, measurement: _SD }
    TS_GF1_0x60_2_Std: { field: TS_SD_GF1_0.60_2, units: false, measurement: _SD }
    TS_GF1_0x75_2_Std: { field: TS_SD_GF1_0.75_2, units: false, measurement: _SD }
    SDP_GF1_1x00_2_Std: { field: SDP_SD_GF1_1.00_2, units: false, measurement: _SD }
    SDP_GF1_0x05_2_Std: { field: SDP_SD_GF1_0.05_2, units: false, measurement: _SD }
    SDP_GF1_0x10_2_Std: { field: SDP_SD_GF1_0.10_2, units: false, measurement: _SD }
    SDP_GF1_0x20_2_Std: { field: SDP_SD_GF1_0.20_2, units: false, measurement: _SD }
    SDP_GF1_0x30_2_Std: { field: SDP_SD_GF1_0.30_2, units: false, measurement: _SD }
    SDP_GF1_0x40_2_Std: { field: SDP_SD_GF1_0.40_2, units: false, measurement: _SD }
    SDP_GF1_0x50_2_Std: { field: SDP_SD_GF1_0.50_2, units: false, measurement: _SD }
    SDP_GF1_0x60_2_Std: { field: SDP_SD_GF1_0.60_2, units: false, measurement: _SD }
    SDP_GF1_0x75_2_Std: { field: SDP_SD_GF1_0.75_2, units: false, measurement: _SD }
    SEC_GF1_1x00_2_Std: { field: SEC_SD_GF1_1.00_2, units: false, measurement: _SD }
    SEC_GF1_0x05_2_Std: { field: SEC_SD_GF1_0.05_2, units: false, measurement: _SD }
    SEC_GF1_0x10_2_Std: { field: SEC_SD_GF1_0.10_2, units: false, measurement: _SD }
    SEC_GF1_0x20_2_Std: { field: SEC_SD_GF1_0.20_2, units: false, measurement: _SD }
    SEC_GF1_0x30_2_Std: { field: SEC_SD_GF1_0.30_2, units: false, measurement: _SD }
    SEC_GF1_0x40_2_Std: { field: SEC_SD_GF1_0.40_2, units: false, measurement: _SD }
    SEC_GF1_0x50_2_Std: { field: SEC_SD_GF1_0.50_2, units: false, measurement: _SD }
    SEC_GF1_0x60_2_Std: { field: SEC_SD_GF1_0.60_2, units: false, measurement: _SD }
    SEC_GF1_0x75_2_Std: { field: SEC_SD_GF1_0.75_2, units: false, measurement: _SD }
    SWC_GF1_1x00_2_Std: { field: SWC_SD_GF1_1.00_2, units: false, measurement: _SD }
    SWC_GF1_0x05_2_Std: { field: SWC_SD_GF1_0.05_2, units: false, measurement: _SD }
    SWC_GF1_0x10_2_Std: { field: SWC_SD_GF1_0.10_2, units: false, measurement: _SD }
    SWC_GF1_0x20_2_Std: { field: SWC_SD_GF1_0.20_2, units: false, measurement: _SD }
    SWC_GF1_0x30_2_Std: { field: SWC_SD_GF1_0.30_2, units: false, measurement: _SD }
    SWC_GF1_0x40_2_Std: { field: SWC_SD_GF1_0.40_2, units: false, measurement: _SD }
    SWC_GF1_0x50_2_Std: { field: SWC_SD_GF1_0.50_2, units: false, measurement: _SD }
    SWC_GF1_0x60_2_Std: { field: SWC_SD_GF1_0.60_2, units: false, measurement: _SD }
    SWC_GF1_0x75_2_Std: { field: SWC_SD_GF1_0.75_2, units: false, measurement: _SD }

