# CH-AWS
# 10_meteo


AWS10-RAW-TOA5-DAT-TBL1-1MIN-201701260236:
  # TOA5
  # First file: CH-AWS_iDL_BOX1_0_1_TBL1_20170126-0236.dat (the very first CH-AWS_iDL_BOX1_0_1_TBL1_*.dat file)
  # Last file:  *currently running*
  filetype_valid_from: 2017-01-26 02:36:00
  filetype_valid_to: 2099-12-31 23:59:59
  filetype_id: CH-AWS_iDL_BOX1_0_1_TBL1_*.dat
  filetype_dateparser: CH-AWS_iDL_BOX1_0_1_TBL1_%Y%m%d-%H%M.dat
  filetype_gzip: false
  db_bucket: ch-aws_raw
  filegroup: 10_meteo
  data_raw_freq: T
  data_skiprows: [ 0, 3 ]
  data_headerrows: [ 0, 1 ]
  data_index_col: 0
  data_parse_dates: [ 0 ]
  data_date_parser: '%Y-%m-%d %H:%M:%S'
  data_build_timestamp: false
  data_keep_good_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: utf-8
  data_delimiter: ','
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    BV_CR1000_BOX_0_1_Avg: { field: BV_CR1000_BOX_0_1, units: false, measurement: _instrumentmetrics }
    BV_CR1000_BOX_0_1_Std: { field: BV_CR1000_SD_BOX_0_1, units: false, measurement: _instrumentmetrics }
    DNTP_CR1000_BOX_0_1: { field: DNTP_CR1000_BOX_0_1, units: false, measurement: _instrumentmetrics }
    G_GF2_0x05_1_Avg: { field: G_GF2_0.05_1, units: false, measurement: G }
    G_GF2_0x05_1_Std: { field: G_SD_GF2_0.05_1, units: false, measurement: _SD }
    LW_IN_M1B2_1x40_1_Avg: { field: LW_IN_M1B2_1.40_1, units: false, measurement: LW }
    LW_IN_M1B2_1x40_1_Std: { field: LW_IN_SD_M1B2_1.40_1, units: false, measurement: _SD }
    LW_IN_RAW_M1B2_1x40_1_Avg: { field: LW_IN_RAW_M1B2_1.40_1, units: false, measurement: _RAW }
    LW_IN_RAW_M1B2_1x40_1_Std: { field: LW_IN_RAW_SD_M1B2_1.40_1, units: false, measurement: _RAW }
    LW_OUT_M1B2_1x40_1_Avg: { field: LW_OUT_M1B2_1.40_1, units: false, measurement: LW }
    LW_OUT_M1B2_1x40_1_Std: { field: LW_OUT_SD_M1B2_1.40_1, units: false, measurement: _SD }
    LW_OUT_RAW_M1B2_1x40_1_Avg: { field: LW_OUT_RAW_M1B2_1.40_1, units: false, measurement: _RAW }
    LW_OUT_RAW_M1B2_1x40_1_Std: { field: LW_OUT_RAW_SD_M1B2_1.40_1, units: false, measurement: _RAW }
    OSO_CR1000_BOX_0_1_Max: { field: OSO_CR1000_MAX_BOX_0_1, units: false, measurement: OSO }
    PPFD_IN_M1B2_1x40_1_Avg: { field: PPFD_IN_M1B2_1.40_1, units: false, measurement: PPFD }
    PPFD_IN_M1B2_1x40_1_Std: { field: PPFD_IN_SD_M1B2_1.40_1, units: false, measurement: _SD }
    PPFD_OUT_M1B2_1x40_1_Avg: { field: PPFD_OUT_M1B2_1.40_1, units: false, measurement: PPFD }
    PPFD_OUT_M1B2_1x40_1_Std: { field: PPFD_OUT_SD_M1B2_1.40_1, units: false, measurement: _SD }
    RECORD: { field: RECORD_X_X_X, units: false, measurement: _instrumentmetrics }
    RH_M1B1_1x50_1_Avg: { field: RH_M1B1_1.50_1, units: false, measurement: RH }
    RH_M1B1_1x50_1_Std: { field: RH_SD_M1B1_1.50_1, units: false, measurement: _SD }
    SDP_GF2_0x05_1_Avg: { field: SDP_GF2_0.05_1, units: false, measurement: SDP }
    SDP_GF2_0x05_1_Std: { field: SDP_SD_GF2_0.05_1, units: false, measurement: _SD }
    SV_CR1000_BOX_0_1_Avg: { field: SV_CR1000_BOX_0_1, units: false, measurement: _instrumentmetrics }
    SV_CR1000_BOX_0_1_Std: { field: SV_CR1000_SD_BOX_0_1, units: false, measurement: _instrumentmetrics }
    SW_IN_M1B2_1x40_1_Avg: { field: SW_IN_M1B2_1.40_1, units: false, measurement: SW }
    SW_IN_M1B2_1x40_1_Std: { field: SW_IN_SD_M1B2_1.40_1, units: false, measurement: _SD }
    SW_OUT_M1B2_1x40_1_Avg: { field: SW_OUT_M1B2_1.40_1, units: false, measurement: SW }
    SW_OUT_M1B2_1x40_1_Std: { field: SW_OUT_SD_M1B2_1.40_1, units: false, measurement: _SD }
    SWC_GF2_0x05_1_Avg: { field: SWC_GF2_0.05_1, units: false, measurement: SWC }
    SWC_GF2_0x05_1_Std: { field: SWC_SD_GF2_0.05_1, units: false, measurement: _SD }
    T_CR1000_BOX_0_1_Avg: { field: T_CR1000_BOX_0_1, units: false, measurement: _instrumentmetrics }
    T_CR1000_BOX_0_1_Std: { field: T_CR1000_SD_BOX_0_1, units: false, measurement: _instrumentmetrics }
    T_RAD_M1B2_1x40_1_Avg: { field: T_RAD_M1B2_1.40_1, units: false, measurement: _instrumentmetrics }
    T_RAD_M1B2_1x40_1_Std: { field: T_RAD_SD_M1B2_1.40_1, units: false, measurement: _instrumentmetrics }
    T_RAD_M1B2_1x40_2_Avg: { field: T_RAD_M1B2_1.40_2, units: false, measurement: _instrumentmetrics }
    T_RAD_M1B2_1x40_2_Std: { field: T_RAD_SD_M1B2_1.40_2, units: false, measurement: _instrumentmetrics }
    TA_M1B1_1x50_1_Avg: { field: TA_M1B1_1.50_1, units: false, measurement: TA }
    TA_M1B1_1x50_1_Std: { field: TA_SD_M1B1_1.50_1, units: false, measurement: _SD }
    TS_GF2_0x05_1_Avg: { field: TS_GF2_0.05_1, units: false, measurement: TS }
    TS_GF2_0x05_1_Std: { field: TS_SD_GF2_0.05_1, units: false, measurement: _SD }
    TS_GF2_0x025_1_Avg: { field: TS_GF2_0.025_1, units: false, measurement: TS }
    TS_GF2_0x025_1_Std: { field: TS_SD_GF2_0.025_1, units: false, measurement: _SD }
    WP_GF2_0x05_1_Avg: { field: WP_GF2_0.05_1, units: false, measurement: WP }
    WP_GF2_0x05_1_Std: { field: WP_SD_GF2_0.05_1, units: false, measurement: _SD }
