# CH-DAV
# 12_meteo_forestfloor


DAV12-RAW-FF1-TOA5-DAT-TBL2-25H-201802281104:
  # TOA5
  # First file: CH-DAV_iDL_FF1_0_1_TBL2_2018_02_28_1104.dat (the very first CH-DAV_iDL_FF1_0_1_TBL2_*.dat)
  # Last file:  *currently running*
  filetype_valid_from: 2018-02-28 11:04:00
  filetype_valid_to: 2099-12-31 23:59:59
  filetype_id: CH-DAV_iDL_FF1_0_1_TBL2_*.dat
  filetype_dateparser: CH-DAV_iDL_FF1_0_1_TBL2_%Y_%m_%d_%H%M.dat
  filetype_gzip: false
  db_bucket: ch-dav_raw
  filegroup: 12_meteo_forestfloor
  data_raw_freq: 25H
  data_skiprows: [ 0, 3 ]
  data_headerrows: [ 0, 1 ]
  data_index_col: 0
  data_parse_dates: [ 0 ]
  data_date_parser: '%Y-%m-%d %H:%M:%S'
  data_build_timestamp: false
  data_keep_good_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: utf-8
  data_delimiter: ','
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    CAL_G_SF_1_1_1: { field: CAL_G_SF_FF1_0.06_1, units: false, measurement: _instrumentmetrics }
    CAL_I_HEATAVG_1_1_1: { field: CAL_I_HEATAVG_FF1_0.06_1, units: false, measurement: _instrumentmetrics }
    CAL_I_HEATAVG_FF1_0x06_1: { field: CAL_I_HEATAVG_FF1_0.06_1, units: false, measurement: _instrumentmetrics }
    CAL_I_HEATT1_1_1_1: { field: CAL_I_HEATT1_FF1_0.06_1, units: false, measurement: _instrumentmetrics }
    CAL_I_HEATT1_FF1_0x06_1: { field: CAL_I_HEATT1_FF1_0.06_1, units: false, measurement: _instrumentmetrics }
    CAL_I_HEATT0_1_1_1: { field: CAL_I_HEATT0_FF1_0.06_1, units: false, measurement: _instrumentmetrics }
    CAL_I_HEATT0_FF1_0x06_1: { field: CAL_I_HEATT0_FF1_0.06_1, units: false, measurement: _instrumentmetrics }
    CAL_SENS_HFP_FF1_0x06_1: { field: CAL_G_SF_FF1_0.06_1, units: false, measurement: _instrumentmetrics }
    CAL_V_SENSDIFF_1_1_1: { field: CAL_V_SENSDIFF_FF1_0.06_1, units: false, measurement: _instrumentmetrics }
    CAL_V_SENSDIFF_FF1_0x06_1: { field: CAL_V_SENSDIFF_FF1_0.06_1, units: false, measurement: _instrumentmetrics }
    CAL_V_SENST1_1_1_1: { field: CAL_V_SENST1_FF1_0.06_1, units: false, measurement: _instrumentmetrics }
    CAL_V_SENST1_FF1_0x06_1: { field: CAL_V_SENST1_FF1_0.06_1, units: false, measurement: _instrumentmetrics }
    CAL_V_SENST2_1_1_1: { field: CAL_V_SENST2_FF1_0.06_1, units: false, measurement: _instrumentmetrics }
    CAL_V_SENST2_FF1_0x06_1: { field: CAL_V_SENST2_FF1_0.06_1, units: false, measurement: _instrumentmetrics }
    CAL_V_SENST0_1_1_1: { field: CAL_V_SENST0_FF1_0.06_1, units: false, measurement: _instrumentmetrics }
    CAL_V_SENST0_FF1_0x06_1: { field: CAL_V_SENST0_FF1_0.06_1, units: false, measurement: _instrumentmetrics }
    DNTP_LOGGER_FF1_0_1: { field: DNTP_LOGGER_FF1_0_1, units: false, measurement: _instrumentmetrics }
    RECORD: { field: RECORD_X_X_X, units: false, measurement: _instrumentmetrics }
    SV_LOGGER_FF1_0_1: { field: SV_LOGGER_FF1_0_1, units: false, measurement: _instrumentmetrics }
    T_LOGGER_FF1_0_1: { field: T_LOGGER_FF1_0_1, units: false, measurement: _instrumentmetrics }
