# CH-DAV
# 12_meteo_forestfloor


DAV12-RAW-FF2-TOA5-DAT-TBL1-1MIN-201903070001:
  # TOA5
  # First file: CH-DAV_iDL_FF2_0_1_TBL1_2019_03_07_0001.dat
  # Last file:  CH-DAV_iDL_FF2_0_1_TBL1_2021_10_22_0001.dat
  # SWC units changed from m3 m-3 to %
  filetype_valid_from: 2019-03-07 00:01:00
  filetype_valid_to: 2021-10-22 00:01:00
  filetype_id: CH-DAV_iDL_FF2_0_1_TBL1_*.dat
  filetype_dateparser: CH-DAV_iDL_FF2_0_1_TBL1_%Y_%m_%d_%H%M.dat
  filetype_gzip: false
  db_bucket: ch-dav_raw
  filegroup: 12_meteo_forestfloor
  data_raw_freq: T
  data_skiprows: [ 0, 3 ]
  data_headerrows: [ 0, 1 ]
  data_index_col: 0
  data_parse_dates: [ 0 ]
  data_date_parser: '%Y-%m-%d %H:%M:%S'
  data_build_timestamp: false
  data_keep_good_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: utf-8
  data_delimiter: ','
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    DNTP_LOGGER_FF2_0_1: { field: DNTP_LOGGER_FF2_0_1, units: false, gain: 1, measurement: _instrumentmetrics }
    FLAG_G_ISCAL_ETH_2_1_1: { field: FLAG_G_ISCAL_ETH_FF2_0.06_1, units: false, gain: 1, measurement: _instrumentmetrics }
    G_2_1_1_Avg: { field: G_FF2_0.06_1, units: false, gain: 1, measurement: G }
    G_2_1_1_Std: { field: G_SD_FF2_0.06_1, units: false, gain: 1, measurement: _SD }
    G_ISCAL_2_1_1: { field: G_ISCAL_FF2_0.06_1, units: false, gain: 1, measurement: _instrumentmetrics }
    G_IU_2_1_1_Avg: { field: G_IU_FF2_0.06_1, units: false, gain: 1, measurement: _RAW }
    G_SF_2_1_1: { field: G_SF_FF2_0.06_1, units: false, gain: 1, measurement: _instrumentmetrics }
    RECORD: { field: RECORD_FF2_0_1, units: false, gain: 1, measurement: _instrumentmetrics }
    SV_LOGGER_FF2_0_1: { field: SV_LOGGER_FF2_0_1, units: false, gain: 1, measurement: _instrumentmetrics }
    SWC_2_1_1_Avg: { field: SWC_FF2_0.05_1, units: false, gain: 1, measurement: SWC }
    SWC_2_1_1_Std: { field: SWC_SD_FF2_0.05_1, units: false, gain: 1, measurement: _SD }
    SWC_2_1_2_Avg: { field: SWC_FF2_0.04_2, units: false, gain: 1, measurement: SWC }
    SWC_2_1_2_Std: { field: SWC_SD_FF2_0.04_2, units: false, gain: 1, measurement: _SD }
    SWC_2_2_1_Avg: { field: SWC_FF2_0.10_1, units: false, gain: 1, measurement: SWC }
    SWC_2_2_1_Std: { field: SWC_SD_FF2_0.10_1, units: false, gain: 1, measurement: _SD }
    SWC_2_3_1_Avg: { field: SWC_FF2_0.21_1, units: false, gain: 1, measurement: SWC }
    SWC_2_3_1_Std: { field: SWC_SD_FF2_0.21_1, units: false, gain: 1, measurement: _SD }
    SWC_2_4_1_Avg: { field: SWC_FF2_0.50_1, units: false, gain: 1, measurement: SWC }
    SWC_2_4_1_Std: { field: SWC_SD_FF2_0.50_1, units: false, gain: 1, measurement: _SD }
    SWC_2_5_1_Avg: { field: SWC_FF2_0.80_1, units: false, gain: 1, measurement: SWC }
    SWC_2_5_1_Std: { field: SWC_SD_FF2_0.80_1, units: false, gain: 1, measurement: _SD }
    SWC_IU_2_1_1_Avg: { field: SWC_IU_FF2_0.05_1, units: false, gain: 1, measurement: _RAW }
    SWC_IU_2_1_2_Avg: { field: SWC_IU_FF2_0.04_2, units: false, gain: 1, measurement: _RAW }
    SWC_IU_2_2_1_Avg: { field: SWC_IU_FF2_0.10_1, units: false, gain: 1, measurement: _RAW }
    SWC_IU_2_3_1_Avg: { field: SWC_IU_FF2_0.21_1, units: false, gain: 1, measurement: _RAW }
    SWC_IU_2_4_1_Avg: { field: SWC_IU_FF2_0.50_1, units: false, gain: 1, measurement: _RAW }
    SWC_IU_2_5_1_Avg: { field: SWC_IU_FF2_0.80_1, units: false, gain: 1, measurement: _RAW }
    T_LOGGER_FF2_0_1: { field: T_LOGGER_FF2_0_1, units: false, gain: 1, measurement: _instrumentmetrics }
    TS_2_1_1_Avg: { field: TS_FF2_0.03_1, units: false, gain: 1, measurement: TS }
    TS_2_1_1_Std: { field: TS_SD_FF2_0.03_1, units: false, gain: 1, measurement: _SD }
    TS_2_2_1_Avg: { field: TS_FF2_0.05_1, units: false, gain: 1, measurement: TS }
    TS_2_2_1_Std: { field: TS_SD_FF2_0.05_1, units: false, gain: 1, measurement: _SD }
    TS_2_2_2_Avg: { field: TS_FF2_0.06_2, units: false, gain: 1, measurement: TS }
    TS_2_2_2_Std: { field: TS_SD_FF2_0.06_2, units: false, gain: 1, measurement: _SD }
    TS_2_3_1_Avg: { field: TS_FF2_0.11_1, units: false, gain: 1, measurement: TS }
    TS_2_3_1_Std: { field: TS_SD_FF2_0.11_1, units: false, gain: 1, measurement: _SD }
    TS_2_4_1_Avg: { field: TS_FF2_0.21_1, units: false, gain: 1, measurement: TS }
    TS_2_4_1_Std: { field: TS_SD_FF2_0.21_1, units: false, gain: 1, measurement: _SD }
    TS_2_5_1_Avg: { field: TS_FF2_0.53_1, units: false, gain: 1, measurement: TS }
    TS_2_5_1_Std: { field: TS_SD_FF2_0.53_1, units: false, gain: 1, measurement: _SD }
    TS_2_6_1_Avg: { field: TS_FF2_0.80_1, units: false, gain: 1, measurement: TS }
    TS_2_6_1_Std: { field: TS_SD_FF2_0.80_1, units: false, gain: 1, measurement: _SD }
    TS_IU_2_1_1_Avg: { field: TS_IU_FF2_0.03_1, units: false, gain: 1, measurement: _RAW }
    TS_IU_2_2_1_Avg: { field: TS_IU_FF2_0.05_1, units: false, gain: 1, measurement: _RAW }
    TS_IU_2_2_2_Avg: { field: TS_IU_FF2_0.06_2, units: false, gain: 1, measurement: _RAW }
    TS_IU_2_3_1_Avg: { field: TS_IU_FF2_0.11_1, units: false, gain: 1, measurement: _RAW }
    TS_IU_2_4_1_Avg: { field: TS_IU_FF2_0.21_1, units: false, gain: 1, measurement: _RAW }
    TS_IU_2_5_1_Avg: { field: TS_IU_FF2_0.53_1, units: false, gain: 1, measurement: _RAW }
    TS_IU_2_6_1_Avg: { field: TS_IU_FF2_0.80_1, units: false, gain: 1, measurement: _RAW }

