# CH-AWS
# 11_meteo_valley
#
#  AWS valley bottom meteo station in approx. 1200m distance to the EC tower:
#   the agrometeo station that Pavel Michna from University of Bern installed in 2005
# This is mast 3 (M3), but in earlier records data were stored as mast 1 (M1).
# Info about these measurements is given in:
# Michna, P., Eugster, W., Hiller, R. V., Zeeman, M. J., & Wanner, H. (2013). Topoclimatological
#   case-study of Alpine pastures near the Albula Pass in the eastern Swiss Alps. Geographica
#   Helvetica, 68(4), 249–263. https://doi.org/10.5194/gh-68-249-2013


AWS11-RAW-TOA5-DAT-TBL1-30MIN-201909190000:
  # TOA5
  # First file: CH-AWS_iDL_BOX4_0_1_TBL1_20190919-0000.dat (the very first CH-AWS_iDL_BOX4_0_1_TBL1_*.dat file)
  # Last file:  *currently running*
  filetype_valid_from: 2019-09-19 00:00:00
  filetype_valid_to: 2099-12-31 23:59:59
  filetype_id: CH-AWS_iDL_BOX4_0_1_TBL1_*.dat
  filetype_dateparser: CH-AWS_iDL_BOX4_0_1_TBL1_%Y%m%d-%H%M.dat
  filetype_gzip: false
  filegroup: 11_meteo_valley
  data_raw_freq: 30T
  data_skiprows: [ 0, 3 ]
  data_headerrows: [ 0, 1 ]
  data_index_col: 0
  data_parse_dates: [ 0 ]
  data_date_parser: '%Y-%m-%d %H:%M:%S'
  data_build_timestamp: false
  data_keep_good_rows: false
  data_remove_bad_rows: false
  data_na_values: [ -9999, nan, NaN, NAN, -6999, '-' ]
  data_encoding: utf-8
  data_delimiter: ','
  data_mangle_dupe_cols: true
  data_keep_date_col: false
  data_version: raw
  data_vars:
    AirTemp_Avg: { field: TA_M3_2.5_1, units: false, measurement: TA }
    Batt_volt_Min: { field: BV_BOX4_0_1, units: false, measurement: _instrumentmetrics }
    GlobRad_Avg: { field: SW_IN_M3_2.5_1, units: false, measurement: SW }
    GrassTemp_Avg: { field: TG_M3_0.05_1, units: false, measurement: TG }
    LeafWet_1_Avg: { field: LEAF_WET_M3_X_1, units: false, measurement: LEAF_WET }
    LeafWet_2_Avg: { field: LEAF_WET_M3_X_2, units: false, measurement: LEAF_WET }
    Precipitation_Tot: { field: PREC_TOT_M3_2.5_1, units: false, measurement: PREC }
    RECORD: { field: RECORD_BOX4_0_1, units: false, measurement: _instrumentmetrics }
    rH_Avg: { field: RH_M3_2.5_1, units: false, measurement: RH }
    SoilTemp_Avg: { field: TS_M3_0.05_1, units: false, measurement: TS }
    # Station: { field: Station_X_X_X, units: false, measurement: XXX }
    WindDir_Avg: { field: WD_M3_X_1, units: false, measurement: WD }
    # Additional wind dirs WVT:
    WindDir_D1_WVT: { field: WD_D1_M3_X_1, units: false, measurement: _instrumentmetrics }
    WindDir_SD1_WVT: { field: WD_M3_X_1, units: false, measurement: _SD }
    WindSpeed_Avg: { field: WS_M3_X_1, units: false, measurement: WS }
    # This seems to be a duplicate of WindSpeed_Avg:
    # WS_ms_S_WVT: { field: WS_M3_X_2, units: false, measurement: WS }
